CREATE DATABASE IF NOT EXISTS bd01;
USE bd01;

CREATE TABLE IF NOT EXISTS usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    tempo_cadastrado TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
